baseURL = 'https://opera-cal-val.github.io/opera-surface-displacement-blog/'
languageCode = 'en-us'
title = 'OPERA Surface Displacement Blog'
theme = 'hugo-bearcub'
author = 'OPERA Project Science Team'
copyright = 'Copyright Â© 2025,  NASA JPL/Caltech'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    languageName = "en-US ðŸ‡ºðŸ‡¸"
    LanguageCode = "en-US"
    contentDir = "content"
  [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  # The description of your website
  description = "Blog for the OPERA DIST-S1 product"


# Dates are displayed following the format below. For more information about
# formatting, see https://gohugo.io/functions/format/
dateFormat = "2006-01-02"

#   # (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
#   # "herman". The former is what you see on Bear Cub's demo (an optimized
#   # version of Hugo Bear Blog), while the latter has a more modern look based on
#   # Herman Martinus's version of the Blogster Minimal theme for Astro.
themeStyle = "original"

[markup.goldmark.renderer]
unsafe = true